steps:
- name: 'sglahn/platformio-core:latest'  
  dir: firmware
  args: ['run']
artifacts: 
  objects: 
    location: 'gs://firmwares/$TAG_NAME'
    paths: ['./workspace/firmware/.pioenvs/esp32/firmware.bin','./workspace/firmware/.pioenvs/esp8266/firmware.bin']